---

- hosts: all
  become: yes
  gather_facts: true
  tasks:

  - name: Install apache and php package on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php package on CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"




  # - name: Install apache and php package
  #   package:
  #     name:
  #       - "{{ apache_package }}"
  #       - "{{ php_package }}"
  #     state: latest
  #     update_cache: yes
