---

# Run against all hosts in inventory
- hosts: all
  
  # Become sudo
  become: yes

  # Disable (false) or enable (default) gathering facts
  gather_facts: false

  # Tasks to run
  tasks:

  - name: Update repository index
    apt:
      # Similar to apt update
      update_cache: yes

  # Name of the task
  - name: Install apache2 package
    # Module
    apt:
      # Module argument(s)
      name: apache2
      # Get 'latest' version of the package or can specify 'absent' to remove package
      state: latest
  
  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
